# PROVES: C8 real-corpus measurement (2026-10-08-c8-real-corpus-measurement.md, Result and per-category sections): turns measure.tsv and manifest.tsv into the markdown report (share of quality <= 49, Wilson 95% interval, quality percentiles, per-category table). Some narrative lines in it are fixed text, not computed.
# INPUTS: argv[1] = root directory containing manifest.tsv and out/measure.tsv; argv[2] = output markdown path. Pure file processing; the write-up does not say where it ran.
# EFFECTS: reads the two TSV files and writes the markdown report to argv[2] (overwrites it). No network.
# BENIGN: it issues no docker, wsl or host-level kill/stop/prune command; run only inside a throwaway container you created yourself with a unique name such as tjspike1-* (never touch other containers). (Pure analysis: it only reads two TSV files and writes the report.)
# ARCHIVED: preserved verbatim from the spike session.
import sys, math, statistics, collections
root = sys.argv[1]
man = {}
for l in open(root + '/manifest.tsv', encoding='utf-8').read().splitlines()[1:]:
    f, c, lic, au, url, t = l.split('\t')
    man[f] = (c, lic, au, url, t)
rows = []
for l in open(root + '/out/measure.tsv').read().splitlines():
    f, fmt, w, h, sm, q, st = l.split('\t')
    rows.append((f, fmt, int(w), int(h), sm == '1', int(q), st))
n = len(rows)
k = sum(r[5] <= 49 for r in rows)
nat = sum(r[4] for r in rows)


def wilson(k, n, z=1.96):
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    a = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (c - a) / d, (c + a) / d


lo, hi = wilson(k, n)
qs = sorted(r[5] for r in rows)


def pct(p):
    i = (len(qs) - 1) * p
    a = int(i)
    return qs[a] + (qs[min(a + 1, len(qs) - 1)] - qs[a]) * (i - a)


o = []
o.append(f"""# C8 (real corpus): share of PDQ quality <= 49 on real screenshots, diagrams and flat-art images

Date 2026-10-08. Provider named only as HMS-A. No HMS-A call, no DB, no git writes.
Method: container `tjspike3-pdq` (from `tj-spike:1`, `--rm`, `--network none`, corpus mounted read-only); each file through the approved scan-frame pipeline (`magick <fmt>:fd:0[0 for gif/webp] -alpha off -colorspace sRGB [-define sample:offset=0 -sample 512x512!] -depth 8 rgb:fd:1`, no auto-orient, NO resize when both sides <= 512), then the reference PDQ core (`pdqtool raw`, same build as RESULTS2 section 5), quality read from its output. Any IM stderr or non-zero exit is recorded as an error: 0 occurred. Scripts: `spike/scripts3/` (fetch.py, measure.py, report.py). Corpus: `spike/corpus3/dl/` (untrusted downloads, own dir); raw output `spike/corpus3/out/measure.tsv`; manifest `spike/corpus3/manifest.tsv`.

## Result

**{k} of {n} images have quality <= 49 ({100*k/n:.1f}%). Wilson 95% interval for the overall share: {100*lo:.1f}% to {100*hi:.1f}%** (with a zero count the upper bound is the informative part; it bounds THIS selection process, not user uploads).

Quality distribution (n={n}): min {qs[0]}, p10 {pct(.10):.0f}, p25 {pct(.25):.0f}, median {pct(.5):.0f}, p75 {pct(.75):.0f}, max {qs[-1]}. {sum(q == 100 for q in qs)} of {n} are exactly 100. Lowest values: """)
low = sorted(rows, key=lambda r: r[5])[:4]
o.append(', '.join(f"{r[0]} = {r[5]} ({r[2]}x{r[3]}, {'native' if r[4] else 'downsampled to 512x512'})" for r in low) + '.')
o.append("""
### Positive control (the measurement can fail)
Same container, same pipeline, same PDQ, generated this run: 800x600 flat white PNG = quality 0; 800x600 red-blue gradient = 0; flat white with one 50x20 black rectangle = 13. All would be rejected at <= 49 (`corpus3/out/control.tsv`). So the 0 count is not a broken pipeline; compare RESULTS2 section 5, where flat logos and gradients generated by me failed at 93-100%.
""")
o.append("### Per category\n\n| category | n | quality <= 49 | share | min q | median q | native <= 512 (n) | formats |\n|---|---|---|---|---|---|---|---|")
cats = collections.OrderedDict()
for r in rows:
    cats.setdefault(man[r[0]][0], []).append(r)
for c, rs in cats.items():
    kk = sum(r[5] <= 49 for r in rs)
    o.append(f"| {c} | {len(rs)} | {kk} | {100*kk/len(rs):.0f}% | {min(r[5] for r in rs)} | {statistics.median(r[5] for r in rs):.0f} | {sum(r[4] for r in rs)} | {dict(collections.Counter(r[1] for r in rs))} |")
o.append(f"| **all** | {n} | {k} | {100*k/n:.1f}% | {qs[0]} | {statistics.median(qs):.0f} | {nat} | {dict(collections.Counter(r[1] for r in rows))} |\n")
o.append(f"Native <= 512 on both sides (measured at native size, no resize): {nat} of {n}; the other {n-nat} were sampled down to 512x512 (nearest, offset 0). With only {nat} small images the small-image regime is thinly covered. Per-category n is 7 to 8, so per-category shares are anecdotal.\n")
o.append("""### Images at quality <= 49 and why
None. The lowest are pixel art (77), a conky/desktop terminal screenshot (78) and a Firefox-Sync preferences screenshot (79): all hard-edged blocks or large flat panes, yet still well above 49. The members I expected to be risky (flat-blue logo on black, a 57x52 icon, a 64x64 pixel-art GIF, 8-bit sprites) all scored 100. I did not eyeball the images; the remark about the lowest three is from category and the nature of PDQ quality (gradient energy of the downsampled luma), not from inspection.
""")
o.append("## Corpus manifest and per-image table\n\nAll from Wikimedia Commons (search per category, file namespace, bitmap formats, size <= 3 MB, licence CC0 / public domain / CC BY / CC BY-SA). Author and exact page URL per file are in `spike/corpus3/manifest.tsv` (columns file, category, licence, author, URL, title); licence and title are repeated here. Page URL = `https://commons.wikimedia.org/wiki/<Commons title>`. Dimensions are of the original file as downloaded (not a Commons thumbnail).\n\n| file | category | Commons title | licence | WxH | fmt | native<=512 | quality | <=49? |\n|---|---|---|---|---|---|---|---|---|")
for r in rows:
    c, lic, au, url, t = man[r[0]]
    o.append(f"| {r[0]} | {c} | {t.replace('File:', '').replace('|', '/')} | {lic} | {r[2]}x{r[3]} | {r[1]} | {'yes' if r[4] else 'no'} | {r[5]} | {'FAIL' if r[5] <= 49 else 'pass'} |")
o.append(f"""
## What this does NOT cover (selection bias)
- Not a random sample of what users upload. I chose by Commons search terms per category, so these are images Commons contributors found worth uploading: mostly clean, cropped, high-resolution, encyclopaedic. Real uploads include phone screenshots of chat apps, dark-mode UIs with large flat panes, memes with a solid-colour band and a caption, tiny avatars, mostly-blank screenshots and mobile-edited images.
- Large flat regions are what drives PDQ quality to 0. Commons screenshots tend to be full of content; a mostly-empty editor or dialog, a solid-colour meme, or a one-colour logo (which my earlier generated set showed failing at 93-100%) are underrepresented. The real logos here were detailed enough to pass.
- Screenshots skew to Linux/GNOME and Wikimedia sites. No WebP (none passed the search filters), so WebP is unmeasured; animated GIFs are measured on frame 0 only.
- 7 to 8 images per category. Five candidates were removed before measuring, by title/suitability only (a photo of an event, a NARA photo, two scans of official records that might hold personal data, one conspiracy-news-site homepage); not by quality, so no bias on the share. They are in `corpus3/excluded/`. I did not visually inspect the images; content safety rests on Commons titles and the search terms, with a title blocklist for people/sexual/child terms.
- No screenshots of my own machine were taken (avoids paths and names), so the typical "blank editor / calculator" case is not represented.

## Conclusion
In a hand-picked set of {n} real free-licence screenshots, diagrams, charts, maps, slides, logos, pixel art, line art and scans, none scored PDQ quality <= 49 (0%, Wilson 95% upper bound {100*hi:.1f}% for this selection), so ordinary content-rich non-photographic images are unlikely to hit IMAGE_UNSCANNABLE; mostly-flat images, which the controls and the earlier generated set show do fail, are not represented here, so this is not the production rate.
""")
open(sys.argv[2], 'w', encoding='utf-8').write('\n'.join(o))
