/**
 * Test environment typing.
 *
 * `@cloudflare/vitest-pool-workers@0.18.x` types the `env` export (from both
 * `cloudflare:test` and `cloudflare:workers`) as `Cloudflare.Env`. There is no
 * `ProvidedEnv` interface to augment in this version — the older
 * `declare module "cloudflare:workers" { interface ProvidedEnv extends Env {} }`
 * pattern no longer applies. `Cloudflare.Env` is already wired to the Worker's
 * bindings by `../src/worker-configuration.d.ts` (generated by `wrangler types`),
 * so `env` in tests is correctly typed out of the box.
 *
 * This file is the conventional place to type any TEST-ONLY bindings configured
 * via the `miniflare` block in `vitest.config.ts` (and therefore absent from
 * `wrangler.jsonc`): declare them by extending `Cloudflare.Env` below. Empty for
 * the M0 skeleton.
 */
declare namespace Cloudflare {
  interface Env {}
}
