/**
 * Test environment typing.
 *
 * `@cloudflare/vitest-pool-workers@0.18.x` types the `env` export (from both
 * `cloudflare:test` and `cloudflare:workers`) as `Cloudflare.Env`. There is no
 * `ProvidedEnv` interface to augment in this version — the older
 * `declare module "cloudflare:workers" { interface ProvidedEnv extends Env {} }`
 * pattern no longer applies. `Cloudflare.Env` is already wired to the Worker's
 * bindings by `../src/worker-configuration.d.ts` (generated by `wrangler types`),
 * so `env` in tests is correctly typed out of the box.
 *
 * This file is the conventional place to type any TEST-ONLY bindings configured
 * via the `miniflare` block in `vitest.config.ts` (and therefore absent from
 * `wrangler.jsonc`): declare them by extending `Cloudflare.Env` below. Empty for
 * the M0 skeleton.
 */
declare namespace Cloudflare {
  interface Env {}
}

/**
 * Vite's `?raw` suffix — `import src from "../src/index.ts?raw"` yields the
 * file's TEXT rather than its exports.
 *
 * Used by test/route-protection.test.ts, which reads the ROUTER'S OWN SOURCE to
 * enumerate the routes it dispatches. That is the point of that suite: a list of
 * routes maintained by hand would not notice the failure it exists to catch (a
 * new mutating route that forgot the pipeline), because whoever forgot the
 * pipeline would equally have forgotten the list.
 *
 * Declared here rather than pulling in `vite/client`: that would drag Vite's
 * whole ambient surface (import.meta.env, every asset type, CSS modules) into
 * the Worker test scope to obtain one string type.
 */
declare module "*?raw" {
  const content: string;
  export default content;
}
